version: '3.9'
services:
  app:
    build: .
    container_name: rhythm-app
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/rhythm
      - REDIS_URL=redis://redis:6379
      - JWT_ACCESS_SECRET=your_jwt_access_secret
      - JWT_REFRESH_SECRET=your_jwt_refresh_secret
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
  db:
    image: postgres:14
    container_name: rhythm-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rhythm
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:alpine
    container_name: rhythm-redis
    restart: always
    ports:
      - "6379:6379"
volumes:
  pgdata: 